theme: jekyll-theme-minimal
title: Chinedu Nwoye
avatar: assets/img/photo.png
description: Ph.D. Computer Vision and Medical Robotics. Post-doctoral research fellow at ICube Lab, IHU Strasbourg, University of Strasbourg, France.
show_downloads: False
show_social: True
navigation:
  - title: Research 
    url: /
  - title: Projects
    url: projects
  - title: Services
    url: services
  - title: Bio
    url: bio
  - title: CV
    url: assets/pdf/cid_cv.pdf
  - title: Contact
    url: setup
    
email: nwoye.chinedu@gmail.com
linkedin: https://ng.linkedin.com/in/chinedu-nwoye-69471a31
github: https://github.com/nwoyecid
gscholar: https://scholar.google.com/citations?user=9lKxBUoAAAAJ&hl=en
researchgate: https://www.researchgate.net/profile/Chinedu-Nwoye-3
twitter: https://twitter.com/Nwoyecid
icube: https://www.unistra.fr/recherche/doctorat/soutenir-sa-these/soutenance/19112-soutenance-de-these-m-chinedu-innocent-nwoye-ed-269
facebook:
flickr:
instagram:
pinterest:
rss: # just type anything here for a working RSS icon
stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
youtube: # channel/<your_long_string> or user/<user-name>
googleplus: # anything in your profile username that comes after plus.google.com/
